
services:
  - type: web
    name: backend-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.backend.settings
      - key: PYTHONPATH
        value: .
